# Generated by Django 4.2.20 on 2025-05-29 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_fotogragria',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
