# Generated by Django 4.2.20 on 2025-06-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_data_fotogragria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.ImageField(upload_to='fotos/%Y/%m/%d/, blank=True'),
        ),
    ]
